### ISSUE TITLE
authentication with token

### ISSUE THREAD

**Issue by freeacetone** [Xcreen/RestSMS#10]
>To send a SMS you can point to your address and use the /send-Endpoint (eg. http://127.0.0.1:8080/send).
You have to send phoneno and message and if you enable authentication also token as post-parameter (you can use form-data and also x-www-form-urlencoded).

How I can enable authentication with token? Settings not contains this option.

Thanks for nice app!

**Comment by Xcreen** [comment]
Its currently just in the master-branch and has no release yet.  

It will be included in the 2.4.0 release.

**Comment by freeacetone** [comment]
Oh nice. Thanks.
