### ISSUE TITLE
Not sending SMS if screen is off for more than 30 mins 

### ISSUE THREAD

**Issue by jakeharlow28** [Xcreen/RestSMS#15]
g'day mate, having 1 more issue with the app not sending SMS if the phone screen is off for more than 30mins (i have disabled battery optimization). now what happens is when my app sends a sms request to RestSMS my program hangs while it waits for a response and will continue to hang until i press the power button to turn on the screen and then the app will send the text immediately once the screen is on.

**Comment by Xcreen** [comment]
I was not able to reproduce the problem.  
Feel free to reopen the issue, when it´s still present and add some more details like android version, logs etc.
