### ISSUE TITLE
Feature Request: Implement Sending Requests for New Messages in RestSms

### ISSUE THREAD

**Issue by UnelDev** [Xcreen/RestSMS#16]
Is it possible to add a feature that allows sending requests for all newly received messages? I am currently looking for an application that can fulfill this requirement, and RestSms seems to be suitable for the task. For example, when a message is received, the app should send a request to the URL specified in the settings. This request should include the phone number, message, and other relevant information.
thank you !

**Comment by shivkodam** [comment]
@UnelDev If you haven't found already. This app does exactly what you're looking for:

https://f-droid.org/en/packages/tech.bogomolov.incomingsmsgateway/

**Comment by UnelDev** [comment]
Thank you! I hadn't come across this app before. It's exactly what I was looking for. Thanks a lot!
