### ISSUE TITLE
Wrong usage Disclaimer

### ISSUE THREAD

**Issue by umer0586** [Xcreen/RestSMS#8]
This app could potentially be used for [Smishing](https://www.ibm.com/topics/smishing#:~:text=Smishing%20is%20a%20social%20engineering,messages%E2%80%94and%20%E2%80%9Cphishing.%E2%80%9D) attack, therefore please add proper disclaimer message in the app and repository

**Comment by Xcreen** [comment]
Thanks for the information! 
The project is licensed under MIT, which includes a phrase for tort. 
I think that should be fine. Or do you think I need the disclaimer in the app itself as well?

**Comment by umer0586** [comment]
You're right, but it is generally a good practice to include disclaimers and terms of use, especially if the project can potentially be misused. However, it's just a suggestion, not mandatory.
